[theme]
primaryColor = "#1E2250" # Yellow - similar to the Mercado Livre button
backgroundColor = "#ffffff" # Light yellow for background
secondaryBackgroundColor = "#f5f5f5" # Light blue for widget background
textColor = "#2d377a" # Blue - similar to Mercado Livre text
font = "sans serif"